services:
  - type: web
    name: phishguard-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_EMAIL
        value: admin@phishguard.ai
      - key: ADMIN_PASSWORD
        value: Admin@1234
      - key: PYTHON_VERSION
        value: 3.10.12
